### PR TITLE
chore: add typescript definitions

### PR DESCRIPTION
**Pull request by mhw0**

### CODE REVIEW

**Comment by davedoesdev** [comment]
@mhw0 thanks for this, appreciate it. Looks good, I'll merge when I get a moment to test it.

**Comment by davedoesdev** [comment]
@mhw0 merged.
I've not a Typescript user but I've seen `typings` and `types` used in `package.json`. Do you know which one is preferred?

**Comment by mhw0** [comment]
@davedoesdev You're welcome! There's no difference between `typings` and `types`. They're just synonyms.

From the documentation (https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html):
> Note that the "typings" field is synonymous with "types", and could be used as well.

**Comment by mhw0** [comment]
17708d1e69000ed714a492b50de538801def76c4, fb19c951037880186c395e5967b269ffb531d520 My bad. Sorry :/

**Comment by davedoesdev** [comment]
No need to apologise at all!

**Pull request merged**
